### PR TITLE
Update LINGUAS

### PR DESCRIPTION
**Pull request by safak45x**
tr.po pls

### CODE REVIEW

**Comment by louis77** [comment]
Do you want to provide Turkish translations? Great!

Please copy `po/com.github.louis77.tuner.pot` to `po/tr.po` and insert the translations.

**Comment by safak45x** [comment]
[tr.po.zip](https://github.com/louis77/tuner/files/5280691/tr.po.zip)
I translated
You add pls :+1:  :D

**Comment by louis77** [comment]
Perfect, thank you! I'll add the translation in the next couple of days.

**Comment by NathanBnm** [comment]
This can be closed according to #37 Don't know why it didn't close itself

**Pull request closed without merging**
